### PR TITLE
Fix `LngLatBounds.extend()` to Handle Object Coordinates

### LINKED ISSUE #2424: `LngLatBounds.extend()` Does Not Work with a Simple `{ lng: number, lat: number }` Object
This has already been mentioned in the mapbox issues: https://github.com/mapbox/mapbox-gl-js/issues/9787

Let me know if you need more information on this or have any questions.

**maplibre-gl-js version**: 2.4.0

**browser**: Chromium (Arc)

### Steps to Trigger Behavior

 1. Create a `new LngLatBounds()` instance.
 2. Extend the bounds using `bounds.extend()` with a `{ lng: number, lat: number }` object as a parameter.

### Link to Demonstration

[Reproduction JSBin](https://jsbin.com/qofexudowe/edit?html,console,output)
[Demo Video](https://clean.td2.ch/Jxnf8HSw)

I am aware that this is not a very good reproduction. Let me know if you need a better one, and I'll take more time to do so.

### Expected Behavior

I expect the bounds to be extended to the given coordinates. According to TypeScript, the `.extend()` function accepts `LngLatLike` which `{ lng: number, lat: number }` would satisfy.

### Actual Behavior

The bounds are not extended and no error is thrown.

### PR DESCRIPTION
**Pull request by Buffalom**
This PR fixes `LngLatBounds.extend()` to handle `{ lng: number, lat: number }` and `{ lon: number, lat: number }` coordinates.

Fixes #2424.

## Launch Checklist

 - [x] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [x] Briefly describe the changes in this PR.
 - [x] Link to related issues.
 - [ ] Include before/after visuals or gifs if this PR includes visual changes.
 - [x] Write tests for all new functionality.
 - [ ] Document any changes to public APIs.
 - [ ] Post benchmark scores.
 - [x] Add an entry to `CHANGELOG.md` under the `## main` section.

### CODE REVIEW

File: src/geo/lng_lat_bounds.ts [hunk 1]
```diff
@@ -103,7 +103,11 @@ class LngLatBounds {
                     const lngLatObj = (obj as any as LngLatLike);
                     return this.extend(LngLat.convert(lngLatObj));
                 }
+
+            } else if (typeof obj === 'object' && obj !== null) {
```
Comment (HarelM) [inline src/geo/lng_lat_bounds.ts:107]: I think a better check would be to check that lng and lat exists in the object.

**Comment by HarelM** [comment]
Thanks for taking the time to open this PR!
Please add a changelog entry as well, other than that and my eval comment I think it's good to go.

**Comment by Buffalom** [comment]
Thanks for your quick review. I updated the code according to your comment and added the changelog entry. Let me know if there is anything else you would like me to do.

**Review by HarelM — APPROVED** [review]
