### PR TITLE
Fix for uninitialized UniformMatrix4f

### LINKED ISSUE #341: 2.0.0 - text rendered in wrong place when using text-variable-anchor
**maplibre-gl-js version**: 2.0.0+

**browser**: Chrome

### Steps to Trigger Behavior

Using the debug page, start with the map zoomed to a point where no labels are showing. Add a symbol layer using text-variable-anchor.

This was working in 1.15.2

### Link to Demonstration

```html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>MapLibre GL JS debug page</title>
    <meta charset='utf-8'>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel='stylesheet' href='../dist/maplibre-gl.css' />
    <style>
        body {
            margin: 0;
            padding: 0;
        }

        html,
        body,
        #map {
            height: 100%;
        }
    </style>
</head>

<body>
    <div id='map'></div>

    <script src='../dist/maplibre-gl-dev.js'></script>
    <script>
        var map = window.map = new maplibregl.Map({
            container: 'map',
            zoom: 7.5,
            center: [-77.01866, 38.888],
            style: 'https://demotiles.maplibre.org/style.json',
            hash: true
        });

        var c = document.createElement('canvas');
        c.width = 24;
        c.height = 24;

        var ctx = c.getContext('2d');
        ctx.fillStyle = '#a00';
        ctx.strokeStyle = '#fff';
        ctx.lineWidth = 2;
        ctx.ellipse(12, 12, 11, 11, 0, 0, 2 * Math.PI);
        ctx.fill();
        ctx.stroke();

        var redCirc = ctx.getImageData(0, 0, 24, 24);

        ctx.fillStyle = '#0a0';
        ctx.fill();
        ctx.stroke();

        var grnCirc = ctx.getImageData(0, 0, 24, 24);

        map.addControl(new maplibregl.NavigationControl());
        map.addControl(new maplibregl.GeolocateControl());

        var sourceData = {
            "type": "FeatureCollection",
            "features": [
            {
                    "type": "Feature",
                    "properties": {
                        "name": "Dennis",
                        "featureclass": "top"
                    },
                    "geometry": {
                        "type": "Point",
                        "coordinates": [-77.01866, 38.888]
                    },
                    "id": 163
                },
                {
                    "type": "Feature",
                    "properties": {
                        "name": "Point A",
                        "featureclass": "base"
                    },
                    "geometry": {
                        "type": "Point",
                        "coordinates": [-77.01866, 38.988]
                    },
                    "id": 163
                },
                {
                    "type": "Feature",
                    "properties": {
                        "name": "Point B",
                        "featureclass": "base"
                    },
                    "geometry": {
                        "type": "Point",
                        "coordinates": [-77.01866, 38.788]
                    },
                    "id": 164
                },
                {
                    "type": "Feature",
                    "properties": {
                        "name": "Point C",
                        "featureclass": "base"
                    },
                    "geometry": {
                        "type": "Point",
                        "coordinates": [-77.15866, 38.888]
                    },
                    "id": 165
                },
                {
                    "type": "Feature",
                    "properties": {
                        "name": "Point D",
                        "featureclass": "base"
                    },
                    "geometry": {
                        "type": "Point",
                        "coordinates": [-76.87866, 38.888]
                    },
                    "id": 166
                },
            ]
        };

        map.on('load', function () {
            map.addImage('redCirc', redCirc);
            map.addImage('grnCirc', grnCirc);
            map.addSource('places', {
                'type': 'geojson',
                'data': sourceData
            });

            map.addLayer({
                'id': 'top_labels',
                'type': 'symbol',
                'source': 'places',
                'filter': ['!=', ['get', 'featureclass'], 'base'],
                'layout': {
                    'text-allow-overlap': true,
                    'text-variable-anchor': ['top', 'bottom', 'left', 'right'],
                    'text-field': ['get', 'name'],
                    'text-font': ['Open Sans Semibold'],
                    'text-offset': [1.2, 1.4],
                    'text-size': 12,
                    'icon-allow-overlap': true,
                    'icon-image': 'grnCirc',
                },
                'paint': {
                    'text-halo-color': '#fff',
                    'text-halo-width': 2
                }
            });

            map.showCollisionBoxes = true;
        });

    </script>
</body>

</html>
```

### Expected Behavior

Text should be shown below the icon, as the rendered collision box indicates.

### Actual Behavior

No text below the icon.
image

It's actually drawn in the upper left corner of the map view. 
image

Note that zooming out until another label is visible somehow kicks the control into working correctly. Can also call map.setLayoutProperty to remove and re-add the text-variable-anchor property to get it going. So it's just the initial load that's broken - failure to initialize some position information somewhere?
image

### PR DESCRIPTION
**Pull request by drwestco**
UniformMatrix4f expects to be initialized with an all-zeros array, while mat4.create() creates an identity matrix. Subsequent calls to UniformMatrix4f.set with an identity matrix will become no-op as gl.uniformMatrix4fv won't be called.

Fixes #341 

## Launch Checklist

 - [X] confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [X] briefly describe the changes in this PR
 - [ ] include before/after visuals or gifs if this PR includes visual changes
 - [ ] write tests for all new functionality
 - [ ] document any changes to public APIs
 - [ ] post benchmark scores
 - [ ] manually test the debug page
 - [ ] apply changelog label ('bug', 'feature', 'docs', etc) or use the label 'skip changelog'
 - [ ] add an entry inside this element for inclusion in the `maplibre-gl-js` changelog: `<changelog></changelog>`

### CODE REVIEW

File: src/render/uniform_binding.ts [hunk 1]
```diff
@@ -109,7 +109,7 @@ class UniformColor extends Uniform<Color> {
     }
 }
 
-const emptyMat4 = mat4.create();
+const emptyMat4 = new Float32Array(16) as mat4;
```
Comment (wipfli) [inline src/render/uniform_binding.ts:112]: Before the typescript migration this was `const emptyMat4 = new Float32Array(16);`. Seems good then.

**Comment by wipfli** [comment]
Very cool that you found that reverting this change fixes the problem. How did you do this?

**Review by wipfli — APPROVED** [review]

**Comment by drwestco** [comment]
> Very cool that you found that reverting this change fixes the problem. How did you do this?

Trial and error, then code review of #209 - everything that could possibly be related to symbol layout + render in that change that was actually a code change and not just type signatures+formatting.

**Comment by HarelM** [comment]
I've reverted anything that caused a test to fail.
This didn't.
Can you please add a test for this?
Sorry to be the bad guy...

**Review by HarelM — CHANGES_REQUESTED** [review]
Add unit test

**Review by HarelM — APPROVED** [review]
Great! Thanks!
