### PR TITLE
Fix Firefox "Alpha-premult deprecated for non-DOM uploads" warning (#2030)

### LINKED ISSUE #2030: Firefox WebGL warning (Alpha-premult and y-flip are deprecated for non-DOM-Element uploads).
When running in Firefox we get the following warning:
**_WebGL warning: texImage: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads._**

Google shows up the following:
https://bugzilla.mozilla.org/show_bug.cgi?id=1400077
https://github.com/mapbox/mapbox-gl-js/issues/5292

Is this an issue or a performance limitation we should be concerned about (as the Firefox developers say this path isn't optimized and should not be used)?

### PR DESCRIPTION
**Pull request by birkskyum**
Firefox logs a warning every time we ask WebGL to handle alpha premultiplication for raw pixel data (sprite atlases, color ramps, etc). It only wants us to use that WebGL flag for actual DOM elements like images and canvases For raw byte arrays, it expects us to do it ourselves.

This moves premultiplication into JS for raw data uploads, keeping the WebGL path for DOM elements.

Fixes #2030
- #2030

Before

Screenshot 2026-02-13 at 21 46 45

After
Screenshot 2026-02-13 at 21 44 20

## Launch Checklist

 - [X] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [X] Briefly describe the changes in this PR.
 - [X] Link to related issues.
 - [X] Include before/after visuals or gifs if this PR includes visual changes.
 - [X] Write tests for all new functionality.
 - [ ] Document any changes to public APIs.
 - [ ] Post benchmark scores.
 - [X] Add an entry to `CHANGELOG.md` under the `## main` section.

### CODE REVIEW

File: src/render/texture.ts [hunk 1]
```diff
@@ -59,23 +60,32 @@ export class Texture {
...
 
         if (resize) {
             this.size = [width, height];
 
-            if (image instanceof HTMLImageElement || image instanceof HTMLCanvasElement || image instanceof HTMLVideoElement || image instanceof ImageData || isImageBitmap(image)) {
+            if (isDomSource) {
                 gl.texImage2D(gl.TEXTURE_2D, 0, this.format, this.format, gl.UNSIGNED_BYTE, image);
             } else {
-                gl.texImage2D(gl.TEXTURE_2D, 0, this.format, width, height, 0, this.format, gl.UNSIGNED_BYTE, (image as DataTextureImage).data);
+                let data = (image as DataTextureImage).data;
```
Comment (HarelM) [inline src/render/texture.ts]: Is it possible to avoid this casting somehow? Maybe invert the if?

Comment (birkskyum) [reply src/render/texture.ts]: We can use a "hasDataProperty" type guard instead, then there's no untyped cast.

File: src/render/texture.test.ts [hunk 2]
```diff
@@ -51,4 +51,14 @@ describe('Texture', () => {
         texture.bind(gl.LINEAR, gl.CLAMP_TO_EDGE);
         expect(texture.texture).toBe(originalHandle);
     });
+
+    test('premultiplyAlpha produces correct output', () => {
```
Comment (HarelM) [inline src/render/texture.test.ts:55]: This test needs to be next to its method, in image.test.ts or something...

**Comment by HarelM** [comment]
Thanks for this PR!
How confident are you about the performance of this? While I understand it might be good to resolve a Firefox warning, if this is worse for chrome, which is a lot more popular, I'm not sure it's worth it. What do you think?

**Comment by birkskyum** [comment]
As far as I can tell it should be fine. Firefox only optimizes the CPU path we're now using (JS premult), so they benefit. For Chrome, I ran the Paint benchmark comparing main vs this branch:

Screenshot 2026-02-14 at 15 03 05]


This branch is actually 3.4% faster (9.50ms vs 9.83ms) - ran it again and saw 2.9% improvement


Why minimal impact:

- Texture uploads happen rarely (just at map load and style changes, not every frame)
- We're processing tiny amounts of data: line gradients are 1KB, sprite atlases load once
- Raster tiles (biggest perf factor) use images/canvas and aren't affected
