### PR TITLE
fix: [issue-2868] after enabling terrain, the _update marker method was not called

### LINKED ISSUE #2868: Marker displacement when switching between 2D and 3D view
**maplibre-gl-js version**: latest/main branch 

**browser**: Mozilla Firefox 114.0 20230605223242 20230605223242 

### Steps to Trigger Behavior

 1.On your local branch `npm start`
 2.Open `3d-Terrain.html` 
 3.Add the following marker 
```javascript 
        const marker = new maplibregl.Marker()
            .setLngLat([11.39067, 47.305513])
            .addTo(map);
```
4. Switch between 2D and 3D, the underlying map changes position but not the marker 
5. Moving the map fixes the marker's position 

### Link to Demonstration

https://output.jsbin.com/vatekax#11.9/47.28354/11.40553/0/52
https://jsbin.com/vatekax/2/edit?html,output

### Expected Behavior
The marker should be at right place when switching between 2D and 3D view 

### Actual Behavior
The marker doesn't change it's screen position but the underlying map does when switching between views 

[Screencast from 16-07-23 04:06:20 PM IST.webm](https://github.com/maplibre/maplibre-gl-js/assets/20891087/a2639ca0-65cc-47b3-8eab-114a54e6f9c6)

Found when working on this: https://github.com/maplibre/maplibre-gl-js/issues/1134 
Might be related

### PR DESCRIPTION
**Pull request by sebastianoscarlopez**
Fixes #2868.

We need to update the marker position after the terrain is loaded; when the map is fully loaded an _idle event_ is fired.

image

So the approach was that after the _terrain event_ is detected by the marker wait till an idle event is reached.

https://github.com/maplibre/maplibre-gl-js/assets/10349981/5d2b7ec7-f179-4379-9e2f-88c46f33f0f6

## Launch Checklist

 - [x] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [x] Briefly describe the changes in this PR.
 - [x] Link to related issues.
 - [x] Include before/after visuals or gifs if this PR includes visual changes.
 - [x] Write tests for all new functionality.
 - [ ] Document any changes to public APIs.
 - [ ] Post benchmark scores.
 - [x] Add an entry to `CHANGELOG.md` under the `## main` section.

### CODE REVIEW

File: src/ui/marker.ts [hunk 1]
```diff
@@ -504,9 +506,15 @@ export class Marker extends Evented {
         return this;
     }
 
-    _update = (e?: { type: 'move' | 'moveend' }) => {
+    _update = (e?: { type: 'move' | 'moveend' | 'terrain' | 'idle' }) => {
         if (!this._map) return;
 
+        if (e?.type === 'terrain') {
+            this._map.on('idle', this._update);
```
Comment (HarelM) [inline src/ui/marker.ts:513]: You can use `once` instead.
But I think idle might prove problematic, IDK... I've heard reports that it might not fire correctly on complicated vector styles.

Comment (HarelM) [reply src/ui/marker.ts]: Worth testing I guess...

**Comment by jashanbhullar** [comment]
I tested this, works fine on the turning terrain on and off but doesn't work on the first render of the map. 

[Screencast from 20-08-23 09:22:32 AM IST.webm](https://github.com/maplibre/maplibre-gl-js/assets/20891087/e9b70391-b044-40ab-a026-4376e7f98636)

File: src/ui/marker.ts (hunk 1 above)
Comment (sebastianoscarlopez) [reply src/ui/marker.ts]: It works and the performance looks good. It will take ≈ 0.1ms by each marker when the user switches between 2D and 3D

https://github.com/maplibre/maplibre-gl-js/assets/10349981/53a36cc9-0902-49a9-9255-8fd48d1d387a

**Comment by sebastianoscarlopez** [comment]
> I tested this, works fine on the turning terrain on and off but doesn't work on the first render of the map.
> 
>  Screencast.from.20-08-23.09.22.32.AM.IST.webm

Thanks @jashanbhullar good catch. I'll try to fix the first render.

**Comment by sebastianoscarlopez** [comment]
First sorry for delaying it, I had little spare time.
I think it's ready, it always works, even in the first renders.

**Comment by HarelM** [comment]
Great!! Can you add some tests to it? Maybe a browser integration test, it at least a unit test?

**Comment by sebastianoscarlopez** [comment]
integration browser test was added. If this test is run in the current main branch it will throw this error.

image

note: I needed to use the idle event, my assumption is that is okay to use it in the test.

**Comment by sebastianoscarlopez** [comment]
Hi @HarelM, please let me know if this fix and its test code are good enough or how it can be improved.

**Comment by HarelM** [comment]
The code looks good, please add a change log entry, and a unit test if possible would be great so that the code in this class continues to be fully covered.

File: CHANGELOG.md [hunk 2]
```diff
@@ -10,6 +10,7 @@
 - Correct type of `Map.addLayer()` and `Style.addLayer()` to allow adding a layer with an embedded source, matching the documentation ([#2966](https://github.com/maplibre/maplibre-gl-js/pull/2966))
 - Throttle map resizes from ResizeObserver to reduce flicker ([#2986](https://github.com/maplibre/maplibre-gl-js/pull/2986))
 - Correct function `Map.setTerrain(options: TerrainSpecification): Map` to be `Map.setTerrain(options: TerrainSpecification | null): Map` per the API spec. ([#2993](https://github.com/maplibre/maplibre-gl-js/pull/2993))
+- Correct marker position when switching between 2D and 3D view ([#2996](https://github.com/maplibre/maplibre-gl-js/pull/2996))
```
Comment (HarelM) [inline CHANGELOG.md:13]: Are you up to date with main? I think 3.3.1 is missing here...

Comment (HarelM) [reply CHANGELOG.md:26]: This should be under main...

**Comment by sebastianoscarlopez** [comment]
@HarelM please take a look at it.

**Comment by HarelM** [comment]
I did, the location of the changelog entry is still incorrect and should be placed above the 3.3.1 heading.

**Comment by sebastianoscarlopez** [comment]
> I did, the location of the changelog entry is still incorrect and should be placed above the 3.3.1 heading.

I'm so dumb 🤦

**Comment by HarelM** [comment]
Not sure why we keep this test, but there's a need to fix it. i.e. change the expected build size...

**Review by HarelM — APPROVED** [review]
