### PR TITLE
Fix tinySdf upgrade and cleaned up a bit.

### LINKED ISSUE #402: Fix tinySdf usage
There need to be an adoption of the breaking changes in tinySdf after the PR to update it to a breaking change version.

### PR DESCRIPTION
**Pull request by HarelM**
## Launch Checklist

Fixes #402 caused by #387 

 - [x] confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [x] briefly describe the changes in this PR

### CODE REVIEW

File: src/render/glyph_manager.ts [hunk 1]
```diff
@@ -187,7 +185,14 @@ class GlyphManager {
             } else if (/light/i.test(stack)) {
                 fontWeight = '200';
             }
-            tinySDF = entry.tinySDF = new GlyphManager.TinySDF(24, 3, 8, .25, family, fontWeight);
+            tinySDF = entry.tinySDF = new GlyphManager.TinySDF({
+                fontSize: 24,
+                buffer: 3,
+                radius: 8,
+                cutoff: 0.25,
+                fontFamily,
```
Comment (wipfli) [inline src/render/glyph_manager.ts:193]: Is this the same as `fontFamily: fontFamily`?

Comment (HarelM) [reply src/render/glyph_manager.ts:193]: Yes, lint is taking care of it to make sure this is used everywhere.

**Review by wipfli — APPROVED** [review]
