### PR TITLE
Fix queryRenderedFeatures for globe view

### LINKED ISSUE #5476: Empty array queryRenderedFeatures on globe projection
**maplibre-gl-js version**: 5.0.1

**browser**: Google Chrome

### Steps to Trigger Behavior

 1.   map.addSource('grid', {
      type: 'vector',
      tiles: [url],
      promoteId: 'gobject_id',
      maxzoom: 5,
    });
 2. map
      .addLayer({
        id: 'grid-layer',
        type: 'fill',
        source: 'grid',
        'source-layer': 'martin.test_function_mvt',
        paint: {
          'fill-color': [
            'case',
            ['boolean', ['feature-state', 'hover'], false],
            MapColors.objectHover,
            MapColors.object,
          ],
          'fill-opacity': 0.5,
          'fill-outline-color': '#000000',
        },
      })
 3.  map.on('mousemove', 'grid-layer', (e) => {
      if (e.features && e.features.length > 0) {
        const feature = e.features.sort((a, b) => area(a) - area(b))[0];
       
          handleHover(feature);
          map.setFeatureState(
            { source: 'grid', sourceLayer: 'martin.test_function_mvt', id: feature.id },
            { hover: true }
          );
        
      }
    });

4. function 
  const handleHover = (feature: maplibregl.MapGeoJSONFeature) => {
    const features = map.current
      ?.queryRenderedFeatures({
        layers: ['grid-layer'],
      })
      ?.filter((item) => item.state.hover === true);
      // i removed the rest of logic of this function
}

### PR DESCRIPTION
**Pull request by msbarry**
## Launch Checklist

Attempt to fix #5476 by switching to unwrapped tile coordinates when checking if a point is inside a rendered tile when using globe view. 

 - [x] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [x] Briefly describe the changes in this PR.
 - [x] Link to related issues.
 - [ ] Include before/after visuals or gifs if this PR includes visual changes.
 - [x] Write tests for all new functionality.
 - [ ] Document any changes to public APIs.
 - [ ] Post benchmark scores.
 - [x] Add an entry to `CHANGELOG.md` under the `## main` section.

### CODE REVIEW

File: src/source/source_cache.ts [hunk 1]
```diff
@@ -993,7 +993,7 @@ export class SourceCache extends Evented {
                 // Tiles held for fading are covered by tiles that are closer to ideal
                 continue;
             }
-            const tileID = tile.tileID;
+            const tileID = transform.isGlobeRendering ? tile.tileID.unwrapTo(0) : tile.tileID;
```
Comment (msbarry) [inline src/source/source_cache.ts:996]: The issue was that this tile was wrapped so the tileSpaceBounds check below was always failing and no tiles matched.

File: src/geo/projection/mercator_transform.ts [hunk 2]
```diff
@@ -210,6 +210,9 @@ export class MercatorTransform implements ITransform {
     public get autoCalculateNearFarZ(): boolean { 
         return this._helper.autoCalculateNearFarZ; 
     }
+    get isGlobeRendering(): boolean {
```
Comment (HarelM) [inline src/geo/projection/mercator_transform.ts:213]: I would like to avoid this is possible as it is specific to globe, which is not relevant to mercator, and creates a weird interface.
I think you can use the projetion's transition state?

File: src/source/source_cache.ts (hunk 1 above)
Comment (HarelM) [reply src/source/source_cache.ts:996]: The tile gets wrapped only for globe but not for mercator?

File: src/geo/projection/mercator_transform.ts (hunk 2 above)
Comment (msbarry) [reply src/geo/projection/mercator_transform.ts:213]: We need some way to tell whether the globe is rendering. I also found trying to use the globe view that application need to be able to tell if globe is rendering through the external API.  How else can we determine that internally and externally?

File: src/source/source_cache.ts (hunk 1 above)
Comment (msbarry) [reply src/source/source_cache.ts:996]: That's what it looks like. If I change this line to just `const tileID = tile.tileID.unwrapTo(0);` then the mercator projection test for querying a point on other side of IDL returns an empty array.

File: src/geo/projection/mercator_transform.ts (hunk 2 above)
Comment (HarelM) [reply src/geo/projection/mercator_transform.ts:213]: What about using `allowRenderWorldCopies()` and `renderWorldCopies`? wouldn't that be more accurate for unwrapping to 0?

File: src/source/source_cache.ts (hunk 1 above)
Comment (HarelM) [reply src/source/source_cache.ts:996]: I guess this is a lesser evil than the rest... :-/

File: src/geo/projection/mercator_transform.ts (hunk 2 above)
Comment (msbarry) [reply src/geo/projection/mercator_transform.ts:213]: `transform.renderWorldCopies` seems to always reflect what the user has set with `map.setRenderWorldCopies(...)`.  I could change `VerticalPerspectiveTransform.renderWorldCopies` to return false always and `GlobeTransform.renderWorldCopies` to return `this.isGlobeRendering ? false : this._helper.renderWorldCopies` and use that instead of isGlobeRendering and these tests pass, but then these tests fail so I'm not sure if this is the expected behavior?

https://github.com/maplibre/maplibre-gl-js/blob/14b641b6c31f47b0854dc90cacd98c43b2089631/src/geo/projection/globe_transform.test.ts#L577-L593

On a side note, is there a way to determine if globe is rendering through external API?

Comment (msbarry) [reply src/geo/projection/mercator_transform.ts]: OK I switched isGlobeRendering to allowRenderWorldCopies. How does that look?

Also `getProjection` always returns globe, but I need to know when it switches between mercator and vertical perspective projection (currently around zoom 12?)

Comment (HarelM) [reply src/geo/projection/mercator_transform.ts]: No need to implement something new, see here:
https://github.com/maplibre/maplibre-gl-js/blob/14b641b6c31f47b0854dc90cacd98c43b2089631/src/geo/projection/covering_tiles.ts#L218

Sorry, took me a second to find it as well...

Comment (HarelM) [reply src/geo/projection/mercator_transform.ts]: I don't think you have a public API, but you can use the following float in the meantime:
`map.style?.projection?.transitionState`, globe is when this is `> 0`

Comment (msbarry) [reply src/geo/projection/mercator_transform.ts]: Ah nice, `transform.getCoveringTilesDetailsProvider().allowWorldCopies()` seems to work!

File: src/source/source_cache.test.ts [hunk 3]
```diff
@@ -1576,6 +1576,119 @@ describe('SourceCache#tilesIn', () => {
         });
         sourceCache.onAdd(undefined);
     }));
+
+    test('globe wrap', () => new Promise<void>(done => {
```
Comment (HarelM) [inline src/source/source_cache.test.ts:1580]: Is it possible to move this promise definition to inside the test instead of here? 
Maybe wrap the on(data...) in a promise using a method and await that? 

I want to reduce the usage of a "top level promise" in the tests as much as possible.

**Comment by HarelM** [comment]
Added a small comment, thanks!!

**Review by HarelM — APPROVED** [review]
Nice solution with the while-await!
