### PR TITLE
Offscreencanvas error fix

### LINKED ISSUE #305: Latest main (Typescript) has some regressions in Firefox
**maplibre-gl-js version**:
current main tagged as v2.0.0-pre.1

**browser**:
Firefox 91.0 MacOS 10.15.7 Catalina
node 14.17.5
npm 6.14.14

### Steps to Trigger Behavior
If you run `npm run start-tests` and connect Firefox, 3 tests fail. They all pass in Chrome. I checked out `1.15.2` and ran them, and Firefox passes. CI does not complain about this.

failed query-tests/regressions/mapbox-gl-js[#5172](https://github.com/mapbox/mapbox-gl-js/issues/5172)
failed query-tests/regressions/mapbox-gl-js[#6075](https://github.com/mapbox/mapbox-gl-js/issues/6075)
failed query-tests/regressions/mapbox-gl-js[#6555](https://github.com/mapbox/mapbox-gl-js/issues/6555)

NOTE: linked issues are to the original mapbox issues

### PR DESCRIPTION
**Pull request by HarelM**
Fixes #305
This is probably due to when this supported method is called.
It used to be using the `window.` in the past which was removed.
This causes this kind of code to fail when using inside workers.
I hope this is the last place...

### CODE REVIEW

**Comment by HarelM** [comment]
@astridx @wipfli please review this fix. Also please see if after using the code in this branch there are other errors that needs to be fixed.

**Comment by astridx** [comment]
@HarelM  Thank you so much for looking so quickly. I think that's is the fix. I haven't tested my examples yet. 

But, I was just working at the repo https://github.com/maplibre/maplibre-gl-js-docs. The Example http://localhost:8080/maplibre-gl-js-docs/example/satellite-map/ was also not OK. With your change, no error is shown and the map is displayed correctly.

**Comment by HarelM** [comment]
Cool! The fix is fairly trivial. I don't think it deserves a comment on the changelog, but I do think it deserves a release.
I can create pre.2 if you think it's the right move.

**Comment by HarelM** [comment]
@astridx please approve this PR and I'll merge it to main and release a new pre-release version

**Review by astridx — APPROVED** [review]

File: src/util/offscreen_canvas_supported.ts [hunk 1]
```diff
@@ -2,7 +2,7 @@ let supportsOffscreenCanvas: boolean | undefined | null;
 
 export default function offscreenCanvasSupported(): boolean {
     if (supportsOffscreenCanvas == null) {
-        supportsOffscreenCanvas = OffscreenCanvas &&
+        supportsOffscreenCanvas = typeof OffscreenCanvas !== 'undefined' &&
```
Comment (wipfli) [inline src/util/offscreen_canvas_supported.ts:5]: Nice. How did you come up with this solution? Also, is there somewhere a list of global objects?

Comment (HarelM) [reply src/util/offscreen_canvas_supported.ts:5]: I faced these issues when I fixed the browser tests (I think). Seems like when this code is used in a worker thread, and now seems like firefox is also anal about it, it fails with this error instead of interpreting this correctly.
You can find other places in the code where I used this for `document` and maybe other stuff.

Comment (HarelM) [reply src/util/offscreen_canvas_supported.ts:5]: I don't know about a list of global objects but everything that you can write `window.something` you can use it as a global variable. The problem with `windows.something` is that in workers you need to write `self.something` which is extremely annoying when writing code that should work in either the window or the worker.
Javascript fun as usual :-)
