### PR TITLE
Get the right zoom when querying elevation

### LINKED ISSUE #6822: Marker placement with terrain enabled throws repeated RangeError for DEM coordinates at low zoom levels
**maplibre-gl-js version**: v5.14.0 (PR #6791)

**browser**: Chrome/Firefox (all modern browsers)

### Description

After PR #6791, placing a Marker on a map with terrain enabled throws a `RangeError: out of range source coordinates for DEM data`. The error occurs repeatedly during render cycles, making the map unresponsive to zoom/pan operations.

The issue is caused by a change in `mercator_transform.ts:326` that calls `terrain.getElevationForLngLat()` instead of `terrain.getElevationForLngLatZoom()`. The new `getElevationForLngLat()` method uses `this.tileManager.maxzoom` (typically 14+) instead of the current viewport tile zoom, causing it to query DEM tiles at high zoom levels where the marker's coordinates may be out of bounds.

### Steps to Trigger Behavior

 1. Create a map with terrain enabled
 2. Place a Marker at any coordinates
 3. Observe the console for repeated RangeError exceptions

### Link to Demonstration

Live demonstration: https://stackblitz.com/edit/web-platform-rwj736qa?file=index.html

Minimal example code:
```html
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8' />
    <title>MapLibre - Marker with Terrain DEM Error</title>
    <meta name='viewport' content='initial-scale=1,maximum-scale=1,user-scalable=no' />
    <script src='https://unpkg.com/maplibre-gl@latest/dist/maplibre-gl.js'></script>
    <link href='https://unpkg.com/maplibre-gl@latest/dist/maplibre-gl.css' rel='stylesheet' />
    <style>
        body { margin:0; padding:0; }
        #map { position:absolute; top:0; bottom:0; width:100%; }
    </style>
</head>
<body>

<div id='map'></div>
<script>
var map = window.map = new maplibregl.Map({
    container: 'map',
    zoom: 2,
    center: [10, 45],
    pitch: 0,
    hash: true,
    style: {
        version: 8,
        sources: {
            osm: {
                type: 'raster',
                tiles: ['https://tile.openstreetmap.org/{z}/{x}/{y}.png'],
                tileSize: 256,
                attribution: '&copy; OpenStreetMap Contributors',
                maxzoom: 19
            },
            terrain_source: {
                type: 'raster-dem',
                url: 'https://tiles.mapterhorn.com/tilejson.json'
            },
            hillshade_source: {
                type: 'raster-dem',
                url: 'https://tiles.mapterhorn.com/tilejson.json'
            }
        },
        layers: [
            {
                id: 'osm',
                type: 'raster',
                source: 'osm'
            },
            {
                id: 'hills',
                type: 'hillshade',
                source: 'hillshade_source',
                layout: {'visibility': 'visible'},
                paint: {'hillshade-shadow-color': '#473B24'}
            }
        ],
        terrain: {
            source: 'terrain_source',
            exaggeration: 1
        }
    },
    maxZoom: 18,
    maxPitch: 85
});

map.addControl(new maplibregl.NavigationControl({
    visualizePitch: true,
    showZoom: true,
    showCompass: true
}));

// Try to place a marker - this will trigger the DEM error
var marker = new maplibregl.Marker();
marker.setLngLat([10, 45]).addTo(map);
</script>

</body>
</html>
```

### Expected Behavior

- Marker should be placed successfully at the specified coordinates
- No console errors should occur
- The map should remain fully functional and allow zooming/panning

### Actual Behavior

After PR #6791, the following occurs:

1. **RangeError is thrown**: "out of range source coordinates for DEM data" from `dem_data.ts:123`
2. **Stack trace shows**: The error originates from `mercator_transform.ts:326` in `locationToScreenPoint()`, which calls `terrain.getElevationForLngLat(lnglat)` 
3. **Root cause**: The new `getElevationForLngLat()` method uses `this.tileManager.maxzoom` (typically 14+) instead of the current tile zoom level, causing it to query DEM tiles at high zoom levels where data may not exist at the marker's coordinates
4. **Map becomes unresponsive**: Once this error occurs repeatedly, the map refuses to zoom or pan properly, as the error handler gets stuck in a loop

**Key issue from PR #6791 change**:
```typescript
// In mercator_transform.ts:326 (before PR #6791)
this.coordinatePoint(MercatorCoordinate.fromLngLat(lnglat), terrain.getElevationForLngLatZoom(lnglat, this._helper._tileZoom), this._pixelMatrix3D)

// After PR #6791
this.coordinatePoint(MercatorCoordinate.fromLngLat(lnglat), terrain.getElevationForLngLat(lnglat), this._pixelMatrix3D)
```

The new `getElevationForLngLat()` method:
```typescript
getElevationForLngLat(lnglat: LngLat) {
    return this.getElevationForLngLatZoom(lnglat, this.tileManager.maxzoom);
}
```

This uses `maxzoom` which causes DEM queries at high zoom levels where the marker's coordinates may be out of bounds for the available DEM tiles.

**Suggested fix**: `mercator_transform.ts:326` should continue using `this._helper._tileZoom` instead of `this.tileManager.maxzoom` when calling terrain elevation methods for marker positioning, or `getElevationForLngLatZoom()` should gracefully handle out-of-bounds coordinates and return a default value instead of throwing.

### PR DESCRIPTION
**Pull request by HarelM**
- Fixes #6822 
- Related to: #6791, #6701

This PR uses covering tiles algorithm to get all the tiles in view to calculate the needed zoom level for a given position.

 - [x] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [x] Briefly describe the changes in this PR.
 - [x] Link to related issues.
 - [x] Write tests for all new functionality.
 - [x] Add an entry to `CHANGELOG.md` under the `## main` section.

### CODE REVIEW

File: src/render/terrain.ts [hunk 1]
```diff
@@ -197,8 +198,11 @@ export class Terrain {
      * @param lnglat - the location
      * @returns the elevation
      */
-    getElevationForLngLat(lnglat: LngLat) {
-        return this.getElevationForLngLatZoom(lnglat, this.tileManager.maxzoom);
+    getElevationForLngLat(lnglat: LngLat, transform: IReadonlyTransform) {
+        const terrainCoveringTiles = coveringTiles(transform, {maxzoom: this.tileManager.maxzoom, minzoom: this.tileManager.minzoom, tileSize: 512, terrain: this});
+        terrainCoveringTiles.sort((a, b) => b.canonical.z - a.canonical.z);
```
Comment (mwilsnd) [inline src/render/terrain.ts]: Why sort here instead of iterating once?

Comment (HarelM) [reply src/render/terrain.ts]: That's a good point, I implemented it as a for loop but it felt like it was too verbose... But you are right, it's faster...

Comment (HarelM) [reply src/render/terrain.ts]: Fixed in 894ffdd
