### PR TITLE
Fix zoom issue with globe + terrain when dragging to poles

### LINKED ISSUE #5839: When globe + terrain are enabled, dragging toward the arctic circle  or antarctica zooms in
When globe + terrain are enabled and you are at a low zoom like 2, grabbing and dragging toawrd the arctic circle or antartica zooms in. it does not do this when only globe is enabled.

Image

**maplibre-gl-js version**: 5.4.0

**browser**: chrome

### Steps to Trigger Behavior / Link to Demonstration

 1. Open https://stackblitz.com/edit/web-platform-21c7kfvt?file=index.html
 2. Grab the map toward the arctic circle and drag downward
 3. while dragging you should see the map zooms in. If you click the terrain button first, it does not do that.

### Expected Behavior

The globe should rotate without zooming it when terrain is enabled, like it does when it is turned off

### Actual Behavior

Map zooms towards the poles when terrain is enabled.

### PR DESCRIPTION
**Pull request by birkskyum**
Closes #5839
- #5839

Closes https://github.com/maplibre/maplibre-gl-js/issues/5026
- https://github.com/maplibre/maplibre-gl-js/issues/5026

Rotating a globe with terrain enabled used to “zoom toward the poles” because the mercator-specific terrain pan logic bypassed the globe helper’s zoom compensation.

This PR redirects all globe+terrain drags through the globe pan helper so the apparent radius stays constant, while keeping the old pixel-delta path for mercator terrain users.

Before

https://github.com/user-attachments/assets/5611978c-8eec-43bb-af5b-5d0578c37d06

After

https://github.com/user-attachments/assets/5dfbbe04-29d5-4b51-a7f5-46fcc98fa89e

## Launch Checklist

 - [X] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [X] Briefly describe the changes in this PR.
 - [X] Link to related issues.
 - [x] Include before/after visuals or gifs if this PR includes visual changes.
 - [x] Write tests for all new functionality. 
 - [ ] Document any changes to public APIs.
 - [ ] Post benchmark scores.
 - [x] Add an entry to `CHANGELOG.md` under the `## main` section.

### CODE REVIEW

File: src/ui/handler_manager.ts [hunk 1]
```diff
@@ -537,19 +537,30 @@ export class HandlerManager {
             tr.center :
             tr.screenPointToLocation(panDelta ? around.sub(panDelta) : around);
 
+        // Two terrain modes share the same zoom/pitch handling; panning differs depending on projection.
```
Comment (HarelM) [inline src/ui/handler_manager.ts]: Due to all the ifs here I think this should be placed in a method of its own and explicitly detail the condition of each if here, i.e:
```ts
if (!terrain) {
    doSomething()
    return;
}
if (terrain && this._map.cameraHelper.useGlobeControls && (!this._terrainMovement && (combinedEventsInProgress.drag || combinedEventsInProgress.zoom)) {
   doSeomthingElse();
   return;
}
```
This way is will be easier to understand which scenario is being handled in each if, which in its current state is very hard to understand.

It might not require a method of its own, but I tend to think it will allow more readable code this way...

**Comment by HarelM** [comment]
While not obvious from the failing CI name, it looks like the code that was changed was not fully covered with tests, if possible please try and cover it with tests.
I still need to understand what I need to fix in order for the coverage annotations to work (instead of codecov which stopped working a while ago)...

File: src/ui/handler_manager.ts (hunk 1 above)
Comment (birkskyum) [reply src/ui/handler_manager.ts]: Good idea - It is broken into three scenarios now, for no-terrain, mercator-terrain, globe-terrain - and made more type safe, so it should be easier to reason about now.

```ts
    _applyTerrainScenario(options: TerrainScenarioOptions) {
        if (!options.terrain) {
            this._applyNoTerrainScenario(options);
            return;
        }

        if (this._map.cameraHelper.useGlobeControls) {
            this._applyGlobeTerrainScenario(options);
            return;
        }

        this._applyMercatorTerrainScenario(options);
    }
```

File: src/ui/handler_manager.ts [hunk 2]
```diff
@@ -572,6 +566,54 @@ export class HandlerManager {
 
     }
 
+    _applyTerrainScenario(options: TerrainScenarioOptions) {
```
Comment (HarelM) [inline src/ui/handler_manager.ts]: `_handleMapControls` maybe as this is applied to non terrain scenario as well...?

Comment (HarelM) [reply src/ui/handler_manager.ts]: `_handleMapMovement`?
`_applyMovementScenario`?
IDK...

Comment (HarelM) [reply src/ui/handler_manager.ts]: BTW, this method looks great now! Thanks!

File: src/ui/handler_manager.test.ts [hunk 3]
```diff
@@ -0,0 +1,218 @@
...
+        handlerName: name,
+        originalEvent: new MapEvent(`${String(name)}start`),
+    };
+}
+
+describe('HandlerManager terrain scenarios', () => {
+    describe('_applyTerrainScenario', () => {
+        it('delegates to no-terrain scenario when terrain is missing', () => {
+            const {manager} = createManager();
+            const noTerrain = vi.spyOn(manager, '_applyNoTerrainScenario');
```
Comment (HarelM) [inline src/ui/handler_manager.test.ts]: Is it possible to spy on the transform methods instead of private methods in the class that is under test?

File: src/ui/handler_manager.test.ts [hunk 4]
```diff
@@ -0,0 +1,218 @@
...
+            expect(globeTerrain).not.toHaveBeenCalled();
+        });
+    });
+
+    describe('_applyGlobeTerrainScenario', () => {
+        it('enables terrain movement and freezes elevation on new drag or zoom', () => {
+            const {manager, handleZoom, handlePan} = createManager(true);
+            const {options} = createTerrainOptions({combinedEventsInProgress: {drag: true}});
+
+            manager._applyGlobeTerrainScenario(options);
```
Comment (HarelM) [inline src/ui/handler_manager.test.ts]: I would advise to keep the check only on the `_handleMapControls` method and not dive into more "private" methods.
Ideally I would even look for a more "public" method (those without the "_" prefix), but I'm not sure this class has those or it's easy enough to configure those, so I'm guessing testing `_handleMapControls` would do in this case, but feel free to explore testing a more "public API" for this class.

**Comment by HarelM** [comment]
Overall, this looks very good, thanks!!

File: src/ui/handler_manager.test.ts (hunk 4 above)
Comment (birkskyum) [reply src/ui/handler_manager.test.ts]: it's just _handleMapControls now

File: src/ui/handler_manager.test.ts (hunk 3 above)
Comment (birkskyum) [reply src/ui/handler_manager.test.ts]: I haven't been able to find a way to do so

**Comment by HarelM** [comment]
I've rewritten the first test to use some existing test infrastructure, here it how it looks:
I think the `createTerrainOptions` so not handle the logic of all the tests, but instead in each test declare only what you need to mock in order for the test to pass, this way the logic in the test files is kept to a minimum thus making sure we are testing the actual code and not the test file code as much as possible.
```ts
describe('HandlerManager terrain scenarios', () => {
    let map: Map;
    beforeEach(() => {
        beforeMapTest();
        map = createMap();
    });

    it('_handleMapControls keeps terrain movement disabled when terrain is not enabled', () => {
        const manager = new HandlerManager(map, {} as any as CompleteMapOptions);
        const {options, setCenterMock} = createTerrainOptions({
            terrain: null,
            combinedEventsInProgress: {drag: true},
        });

        manager._terrainMovement = false;
        map._elevationFreeze = false;
        map.cameraHelper = {
            handleMapControlsRollPitchBearingZoom: vi.fn(),
            handleMapControlsPan: vi.fn(),
            useGlobeControls: false,
        } as unknown as ICameraHelper;
        manager._handleMapControls(options);

        expect(map.cameraHelper.handleMapControlsRollPitchBearingZoom).toHaveBeenCalledWith(options.deltasForHelper, options.tr);
        expect(map.cameraHelper.handleMapControlsPan).toHaveBeenCalledWith(options.deltasForHelper, options.tr, options.preZoomAroundLoc);
        expect(map._elevationFreeze).toBe(false);
        expect(manager._terrainMovement).toBe(false);
        expect(setCenterMock).not.toHaveBeenCalled();
    });
```

File: src/ui/handler_manager.test.ts (hunk 3 above)
Comment (birkskyum) [reply src/ui/handler_manager.test.ts]: They are using the beforeMapTest, createMap now, and checking values like map._elevationFreeze

**Comment by birkskyum** [comment]
Thanks - I have updated to use the beforeMapTest, createMap instead of mocking

**Review by HarelM — APPROVED** [review]
Thanks!!
