### PR TITLE
Fix parameter types of Map.querySourceFeatures

### LINKED ISSUE #1393: Map.querySourceFeatures: all parameters should be optional
According to the documentation of Map.querySourceFeatures the fields sourceLayer (if not a vector tile source) and filter of parameters are optional. 

In the called querySourceFeatures in tile.ts one can see that changing the declaration has no negative consequences, it is just like the whole param(eter)s were not defined.

### PR DESCRIPTION
**Pull request by cns-solutions-admin**
Fixes #1393

### CODE REVIEW

**Comment by cns-solutions-admin** [comment]
Don't think the integration test timeout is caused by this change!

File: src/source/tile.ts [hunk 1]
```diff
@@ -315,16 +315,16 @@ class Tile {
...
+        filter?: Array<any>;
         validate?: boolean;
     }) {
         const featureIndex = this.latestFeatureIndex;
         if (!featureIndex || !featureIndex.rawTileData) return;
 
         const vtLayers = featureIndex.loadVTLayers();
 
-        const sourceLayer = params ? params.sourceLayer : '';
+        const sourceLayer = params && params.sourceLayer ? params.sourceLayer : '';
```
Comment (HarelM) [inline src/source/tile.ts:327]: If there where only type changes I wouldn't have a question here, but since this changes the code I would advise to add a test to cover this case.
Also doesn't this means that `sourceLayer` is a required parameter accroding to the code before the change?

Comment (cns-solutions-admin) [reply src/source/tile.ts:327]: Before, params.sourceLayer was defined as non-optional, but as params itself was and is optional, this means optional.

So this is just to make sure that sourceLayer will still never be undefined (for the following index-access) - and not fail at the index-access, but just return immediately afterwards as before.

Comment (HarelM) [reply src/source/tile.ts:327]: I'm not sure this is correct - although `params` is optional it doesn't mean `sourceLayer` is optional in case `params` is passed to this method - this is basically what the code is saying - `params` is optional but if it is passed it assumes `sourceLayer` is part of the passed `params` object.
My understanding is that the docs were not entirely correct and might need an update.
`filter` on the other hand is optional as can be seen from the check below (`params & params.filter`).
So from my point of view it might be better to change the docs here and not the code?

Comment (cns-solutions-admin) [reply src/source/tile.ts:327]: Yes, and the code change reflects that params = {} (which was not possible before - at least when correctly called from typescript) is handled like a params = undefined.

Functionally the params.sourceLayer is only needed for vector tile layers and this is reflected in the documentation.
And if it is a vector tile layer and no sourceLayer is passed, it still exits gracefully - returning nothing.

File: src/ui/map.ts [hunk 2]
```diff
@@ -1376,8 +1376,8 @@ class Map extends Camera {
      *
      */
     querySourceFeatures(sourceId: string, parameters?: {
-        sourceLayer: string;
-        filter: Array<any>;
+        sourceLayer?: string;
+        filter?: Array<any>;
```
Comment (HarelM) [inline src/ui/map.ts:1380]: Can we improve the filter type from `Array<any>` to something else?
Also would be great to change the docs above here, remove the `Object` and use a type - also use the same type across all calls as the same object is passed, something like `export type QuerySourceFetureParameters` or `export type QuerySourceFetureOptions`...

Comment (cns-solutions-admin) [reply src/ui/map.ts:1380]: Should be ExpressionSpecification, when the appropriate PR is merged. ExpressionFilterSpecification is probably not correct, as according to the documentation boolean is not allowed (and legacy filters neither).

Comment (HarelM) [reply src/ui/map.ts:1380]: Can you update this now as the other PR was merged and now improving this is possible...?

Comment (HarelM) [reply src/ui/map.ts:1380]: @cns-solutions-admin any updates on this?

**Comment by cns-solutions-admin** [comment]
After checking the code, FilterSpecification is the correct parameter type.
Regarding params: there are also other methods with params - if this is desired that should be done in another PR while taking care that no circular (import-) dependencies are created.

**Review by HarelM — APPROVED** [review]

**Comment by HarelM** [comment]
Thanks!! Feel free to continue type improving..  😀

**Comment by wipfli** [comment]
Just to double check, this is not a breaking change, right?

**Comment by HarelM** [comment]
It's not a change, just types, code and docs alignment.
