### PR TITLE
Fix: use correct location for mouse events of line layer with line-offset (#1108)

### LINKED ISSUE #1108: Mouse events are not at the correct location for line layer with a line-offset
**maplibre-gl-js version**: at least 2.1.7, probably all versions

**browser**: at least Chrome, Firefox and Edge

### Steps to Trigger Behavior

 1. Create a line layer with a nonzero line-offset
 2. Listen for `mouseenter` and `mouseleave` events for that layer
 3. Observe that the events are triggered at the wrong location, especially at the end of the line

### Link to Demonstration

https://jsbin.com/kokutixesa/3/edit?html,output

### Expected Behavior

In the demonstration link, when hovering the mouse over the green thick line, the green thick line becomes red with a dash pattern.

### Actual Behavior

In the demonstration link, the `mouseenter` and `mouseleave` events of the layer with the green thick line act like the green thick line starts at the right of the green thick line and ends at the left of the black line.

### Similar Mapbox GL JS issue

https://github.com/mapbox/mapbox-gl-js/issues/9419

### PR DESCRIPTION
**Pull request by jkoelewijn**
### Changelog category

bug

### Changelog

<changelog>Use correct location for mouse events of line layer with line-offset (#1108)</changelog>.

### Technical description

The `offsetLine` function uses a `ring` array that contains instances of the class `Point` from `@mapbox/point-geometry`. Methods of the `Point` class that are prefixed with `_` adjust the instance of the `Point` class in place, i.e. no new instance is created and the current instance is mutated as a side effect and returned. This goes wrong when the `zero` variable is reused.

In the solution of this pull request the `zero` variable is removed and new instances of the `Point` class are created when needed.

### Backport from Mapbox project?

This fixes #1108 using a similar solution as in https://github.com/jack9ye/mapbox-gl-js/commit/ad2df2df734d26c85b9daa81c76eca9dc4f4508d, which is referred to in https://github.com/mapbox/mapbox-gl-js/issues/9419. The code is different, but the solution is very similar.

I guess that does not count as a backport, but I'm not totally sure. Please confirm.

Update: I checked what Mapbox GL JS version jack9ye uses for his proposed solution and unfortunately that is v2.2.0. However, all the code that is visible in https://github.com/jack9ye/mapbox-gl-js/commit/ad2df2df734d26c85b9daa81c76eca9dc4f4508d has not changed since v1.14.0-dev. Furthermore, the solution of this pull request will typically create 2 new `Point` objects per ring and the solution of https://github.com/jack9ye/mapbox-gl-js/commit/ad2df2df734d26c85b9daa81c76eca9dc4f4508d will create 3.

### Tasks

 - [x] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [x] Briefly describe the changes in this PR.
 - [x] Include before/after visuals or gifs if this PR includes visual changes.
     - No visual change, only a change in behavior.
 - [x] Write tests for all new functionality.
 - [x] Document any changes to public APIs.
     - No change to public APIs.
 - [ ] Post benchmark scores.
 - [x] Manually test the debug page.
 - [x] Suggest a changelog category: bug/feature/docs/etc. or "skip changelog".
 - [x] Add an entry inside this element for inclusion in the `maplibre-gl-js` changelog.

### CODE REVIEW

**Comment by HarelM** [comment]
Can you create a test that fails before this fix and passes afterwards?
Also a changelog entry is needed.
P.S. why would creating a new object inside the loop fixes this issue? The zero point is updated somewhere along the process?

**Comment by jkoelewijn** [comment]
@HarelM, this pull request should be improved now. I'm not sure how to post the benchmark scores though...

File: src/style/query_utils.ts [hunk 1]
```diff
@@ -43,3 +43,28 @@ export function translate(queryGeometry: Array<Point>,
     }
     return translated;
 }
+
+export function offsetLine(rings, offset) {
```
Comment (HarelM) [inline src/style/query_utils.ts:47]: Can you add jsdocs and typings to this method?

**Comment by HarelM** [comment]
Also the first checkbox is not ticked...

**Comment by HarelM** [comment]
If the code is different then this is not a backport.

**Review by HarelM — APPROVED** [review]

**Comment by HarelM** [comment]
Changelog file entry is missing, can you please add?
