### PR TITLE
VectorTileWorkerSource: fix reload for original's load parse would not pass the rawTileData and meta

### LINKED ISSUE #2923: `queryRenderFeature` emits `Out of bounds.` Error in 3.2.1 version
Hi,

I noticed that in version 3.2.1 there is an "Out of bounds" error. The error does not always occur because race condition occurs in the code. After a brief investigation, I determined that a change from this PR #1874 caused the problem. 

**maplibre-gl-js version**: 3.2.1

**browser**: all

### Steps to Trigger Behavior

 1. Init map with vector styles
 2. Add empty GeoJSON source to map after load event
 3. Add symbol layer with created source
 4. Add mouse event listener
 5. Update the source by `setData` method
 6. Trigger mouse event on symbol from this layer or use `queryRenderedFeatures` on layer

### Link to Demonstration

[fiddle](https://jsfiddle.net/fpt35enj/)

https://github.com/maplibre/maplibre-gl-js/assets/5881368/df665528-bdd5-470d-9f35-9b1d9961eb7b

### Expected Behavior
No error

### Actual Behavior
`Out of bounds.` Error

### PR DESCRIPTION
**Pull request by ambientlight**
## Launch Checklist

Fixes #2923.

An unfortunate regression has been introduced in #1874, where when `reloadTile`  would get called before the original load completes, the `rawTileData` won't get passed to the main thread, leading to #2923. The base `loadTile` will extend the parse result with previously fetched data at https://github.com/maplibre/maplibre-gl-js/blob/01e5f51cf15421cb40ad0ff4798f8f536f816a0c/src/source/vector_tile_worker_source.ts#L130

This PR will keep the original fetching state until the first parse completes and will pass it along as expected.

 - [X] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [X] Briefly describe the changes in this PR.
 - [X] Link to related issues.
 - [x] Write tests for all new functionality.
 - [x] Add an entry to `CHANGELOG.md` under the `## main` section.

### CODE REVIEW

**Comment by HarelM** [comment]
Can you fix the lint warning?

File: src/source/vector_tile_worker_source.ts [hunk 1]
```diff
@@ -54,6 +54,12 @@ function loadVectorTile(params: WorkerTileParameters, callback: LoadVectorDataCa
     };
 }
 
+interface FetchingState {
```
Comment (HarelM) [inline src/source/vector_tile_worker_source.ts:57]: Can this be a type instead? I aim to use interfaces for things people can inherit publicly.

**Comment by HarelM** [comment]
I see that a "else" part of this fix is not covered by a test, can you add one (see the linked coverage report)?

**Comment by HarelM** [comment]
Thanks a lot for taking care of it in such a short notice!!

**Comment by ambientlight** [comment]
@HarelM: done, thanks!

**Review by HarelM — APPROVED** [review]
