### PR TITLE
Fix horizon-fog-belnd where sky is not set.

### LINKED ISSUE #4517: Can't disable all sky rendering when terrain is enabled
**maplibre-gl-js version**: 4.5.1

**browser**:  Vivaldi 6.8.3381.48

### Steps to Trigger Behavior

 1. Open demonstration
 2. Disable sky with checkbox (this calls `map.setSky(undefined)`)
 3. Notice the sky rendering turns off, but the horizon and fog colouring persists
 4. Disable terrain via the control in the top right, notice that horizon/fog colouring is now gone

### Link to Demonstration

https://jsbin.com/hibilakuno/edit?html,output

### Expected Behavior

The sky/horizon/fog rendering is disabled when terrain is enabled when calling `setSky(undefined)` or `sky: undefined` in a style spec

### Actual Behavior

Only sky rendering is disabled when terrain is enabled

### PR DESCRIPTION
**Pull request by HarelM**
## Launch Checklist

Fixes #4517 by setting `fog-ground-blend` to 1 when sky is undefined to prevent color change near the horizon.
- #4517

This is in countinue to the following PR which solved most of the issues around sky:
- #4587

The following is a before and after of a red background with no sky and terrain enabled.
Before:
image
After:
image

Fixes #4517

 - [x] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [x] Briefly describe the changes in this PR.
 - [x] Link to related issues.
 - [x] Include before/after visuals or gifs if this PR includes visual changes.
 - [x] Write tests for all new functionality.
 - [x] Add an entry to `CHANGELOG.md` under the `## main` section.

### CODE REVIEW

File: src/style/sky.ts [hunk 1]
```diff
@@ -66,6 +66,7 @@ export class Sky extends Evented {
                 'sky-color': 'transparent',
                 'horizon-color': 'transparent',
                 'fog-color': 'transparent',
+                'fog-ground-blend': 1
```
Comment (kubapelc) [inline src/style/sky.ts:69]:
```suggestion
                'fog-ground-blend': 1,
                'atmosphere-blend': 0,
```

This will also disable atmosphere by default on globe, and remove the need for the `setSky` calls in globe examples. Also `map.setSky(undefined);` should work with this change.

**Review by kubapelc — APPROVED** [review]
Looks good to me!
